### ISSUE TITLE
Refactor out the form-generation from Admin.php to Form.php

### ISSUE THREAD

**Issue by zackkatz** [trustedlogin/client#111]
Admin.php is too heavy and is doing too much. As discussed, let's separate concerns regarding template generation.

- Move the template-generating PHP into its own file
- Define the fields in a class property (share debug data, create support ticket, ticket description)
- Perhaps create a method like `Form::get_submitted_fields()` that can be used by the Ajax class so that it can be used to verify requests instead of [defining inline the fields that exist](https://github.com/trustedlogin/client/blob/c1da3d556a8dfe8b44e7bdcf70d1073b84c191bb/src/Ajax.php#L88)

**Comment by Shelob9** [comment]
Related: #112

**Comment by zackkatz** [comment]
Implemented in 1.5.0.
