### ISSUE TITLE
How should we degrade gracefully when Sodium doesn't exist?

### ISSUE THREAD

**Issue by zackkatz** [trustedlogin/client#13]
- [ ] Have button take user directly to vendor support site
- [ ] Hide TL badge if not on SSL #2
- [x] Have auth screen show a different message altogether

I'd like some feedback on this, @inztinkt and @shawnhooper

**Comment by inztinkt** [comment]
I think redirecting to support on click might be confusing for the end user, esp if they're already in a conversation with support.

Might be best to present a message if the button is clicked saying why TrustedLogin cant/wont work and give them the option to close or go to support forum.

At least this information can be shared via chat/ticket/etc and the support agent can give them guidance or point to a helpdesk article or something.

**Comment by zackkatz** [comment]
Right. Once we get rid of the modal experience In favor of the landing page, things should be cleaner.

**Comment by inztinkt** [comment]
@zackkatz any preferences on what this should now look like? 

Shall I just change the button or the content of the auth screen entirely?

**Comment by zackkatz** [comment]
Let's wait on Tracy feedback.

**Comment by zackkatz** [comment]
@inztinkt Let's to "Change the button or the content of the auth screen entirely?"

Have there be a message saying the site doesn't support encryption, have a nice big `button button-primary button-hero` button taking the user to the defined support URL.
