### ISSUE TITLE
Send the site’s health check data as metadata

### ISSUE THREAD

**Issue by zackkatz** [trustedlogin/client#15]
This will only work if it doesn't increase the encryption time linearly.

**Comment by inztinkt** [comment]
Hey @zackkatz is this issue re: sending the healtcheck data to SaaS or about encryption time increases?

**Comment by zackkatz** [comment]
Sending the health check data to SaaS.

The note was me wondering if adding 1–3Kb of text would make the encryption take 100x longer.

**Comment by zackkatz** [comment]
This is implemented via webhook settings currently. Closing until I receive feedback from users that further integration is necessary.
