### ISSUE TITLE
Receiving 'reset' request from SaaS.

### ISSUE THREAD

**Issue by inztinkt** [trustedlogin/client#41]
hey @zackkatz I was looking at building this out a REST API endpoint.

ie `<siteurl>/<api-slug>/tl-<ns>/<version>/revoke`

however, now i'm just working through how:

- the SaaS would know the URL (as it's encrypted and secret to the SaaS).
- if we did have the URL, how would we'd verify that this is coming from SaaS. 
- does this open a new potential attack surface?

Might it be best to let the site access timeout given that the encrypted envelope will be useless once the encryption keys are reset on vendor side?

Also means we can stop caching the public key and also drop issue #39.

**Comment by zackkatz** [comment]
Let's encrypt with private key and do a [sign check]

**Comment by zackkatz** [comment]
Since we have key rotation and it would be heavy server-side to send out resets, I'm putting this on hold until we get vendor feedback that this is desirable.
